#!/usr/bin/env bash
# =============================================================================
# new-project.sh — Project Analysis Workspace Generator
# =============================================================================
# Usage: ./new-project.sh [project-name]
#
# Creates a standardized analysis workspace for any software project.
# 9 directories, 28+ files, 100% boilerplate ready to fill.
#
# Based on the First-Principles Engineering Analysis Framework.
# =============================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'

# ── Defaults ────────────────────────────────────────────────────────────────
PROJECT_NAME="${1:-my-project}"
ANALYSIS_DIR="analysis"

# ── File Template ───────────────────────────────────────────────────────────
# Each file gets a standard header + single guiding question
make_file() {
  local dir="$1" name="$2" question="$3"
  local filepath="$ANALYSIS_DIR/$dir/$name"
  mkdir -p "$(dirname "$filepath")"
  cat > "$filepath" <<TEMPLATE
# ${name%.md} — ${question}

> **${PROJECT_NAME}** — $(echo "${dir#??}" | tr '_' ' ')

## الهدف

${question}

## المحتوى

<!-- اكتب تحليلك هنا -->

---

*Generated by new-project.sh — $(date +%Y-%m-%d)*
TEMPLATE
}

# ── Banner ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}  ╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}  ║      Project Analysis Workspace Generator v1.0        ║${NC}"
echo -e "${CYAN}${BOLD}  ║      First-Principles Engineering Framework           ║${NC}"
echo -e "${CYAN}${BOLD}  ╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Project: ${BOLD}${PROJECT_NAME}${NC}"
echo -e "  Output:  ${BOLD}${ANALYSIS_DIR}/${NC}"
echo ""

# ── Confirm ─────────────────────────────────────────────────────────────────
read -rp "  Create analysis workspace? (Y/n): " confirm
confirm="${confirm:-Y}"
if [[ "$confirm" =~ ^[Nn] ]]; then
  echo -e "  ${YELLOW}Cancelled.${NC}"; exit 0
fi

# ── Create Structure ────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}Creating structure...${NC}"
echo ""

# ────────────────────────────────────────────────────────────────────────────
# 01_Business_and_Vision
# ────────────────────────────────────────────────────────────────────────────
DIR="01_Business_and_Vision"
make_file "$DIR" "Business_Model_Canvas.md" "كيف نكسب المال؟ ما نموذج العمل؟ (BMC)"
make_file "$DIR" "Value_Proposition.md" "ما القيمة التي نقدمها للعميل؟ وما المشكلة التي نحلها؟"
make_file "$DIR" "Market_and_Competitors.md" "من هم المستخدمون؟ من المنافسون؟ TAM/SAM/SOM؟"
make_file "$DIR" "Feasibility_Study.md" "هل المشروع مجدي تقنياً ومالياً؟ تحليل المخاطر التجارية."

# ────────────────────────────────────────────────────────────────────────────
# 02_Requirements_Engineering
# ────────────────────────────────────────────────────────────────────────────
DIR="02_Requirements_Engineering"
make_file "$DIR" "Functional_Requirements.md" "ما المهام التي يجب أن ينفذها النظام؟ (FRs مرقمة)"
make_file "$DIR" "Non_Functional_Requirements.md" "ما متطلبات الأداء، التوافرية، الأمان، قابلية التوسع؟"
make_file "$DIR" "User_Roles_and_Permissions.md" "من هم المستخدمون؟ ما صلاحيات كل دور؟ (RBAC)"
make_file "$DIR" "User_Stories.md" "ما قصص المستخدمين؟ (As a... I want... so that...)"

# ────────────────────────────────────────────────────────────────────────────
# 03_System_Architecture
# ────────────────────────────────────────────────────────────────────────────
DIR="03_System_Architecture"
make_file "$DIR" "Architecture_Decision_Records_ADR.md" "لماذا اخترنا هذه التقنيات؟ توثيق كل قرار معماري."
make_file "$DIR" "State_Machines.md" "ما حالات الكيانات الأساسية وكيف تنتقل؟ (State Diagram)"
make_file "$DIR" "System_Flowcharts.md" "ما تدفقات العمليات المنطقية المعقدة؟ (Flowcharts)"
make_file "$DIR" "Tech_Stack.md" "ما التقنيات المستخدمة؟ (Frontend, Backend, DB, Services)"

# ────────────────────────────────────────────────────────────────────────────
# 04_Database_Design
# ────────────────────────────────────────────────────────────────────────────
DIR="04_Database_Design"
make_file "$DIR" "Entity_Relationship_Diagram_ERD.md" "ما الكيانات والعلاقات بينها؟ (ERD)"
make_file "$DIR" "Data_Dictionary.md" "ما الحقول، الأنواع، القيود لكل جدول؟"
make_file "$DIR" "Caching_Strategy.md" "أين نحتاج التخزين المؤقت؟ Redis? CDN?"

# ────────────────────────────────────────────────────────────────────────────
# 05_API_and_Integrations
# ────────────────────────────────────────────────────────────────────────────
DIR="05_API_and_Integrations"
make_file "$DIR" "RESTful_Endpoints_Draft.md" "ما مسارات API؟ هيكل Request/Response؟"
make_file "$DIR" "Third_Party_Integrations.md" "ما الخدمات الخارجية؟ (بوابات دفع، SMS، إيميل)"
make_file "$DIR" "WebSockets_and_Events.md" "هل نحتاج تحديثات لحظية؟ WebSockets? Events?"

# ────────────────────────────────────────────────────────────────────────────
# 06_UI_UX_Design
# ────────────────────────────────────────────────────────────────────────────
DIR="06_UI_UX_Design"
make_file "$DIR" "User_Journey_Maps.md" "كيف يتفاعل المستخدم مع النظام؟ رحلة كاملة خطوة بخطوة."
make_file "$DIR" "Wireframes_and_Layouts.md" "ما تخطيط الشاشات الرئيسية؟ (روابط أو صور)"
make_file "$DIR" "Information_Architecture.md" "ما هيكل الصفحات وشجرة التنقل؟"

# ────────────────────────────────────────────────────────────────────────────
# 07_DevOps_and_Deployment
# ────────────────────────────────────────────────────────────────────────────
DIR="07_DevOps_and_Deployment"
make_file "$DIR" "Environment_Variables.md" "ما متغيرات البيئة؟ (قالب .env.example)"
make_file "$DIR" "Docker_and_Containers_Strategy.md" "كيف نبني الحاويات؟ Docker Compose؟"
make_file "$DIR" "CI_CD_Pipelines.md" "كيف نختبر وننشر تلقائياً؟ (GitHub Actions)"
make_file "$DIR" "Monitoring_and_Logs.md" "كيف نراقب الأداء ونتتبع الأخطاء؟"

# ────────────────────────────────────────────────────────────────────────────
# 08_Security_and_Risks
# ────────────────────────────────────────────────────────────────────────────
DIR="08_Security_and_Risks"
make_file "$DIR" "Threat_Model.md" "ما التهديدات الأمنية المحتملة؟ وكيف نسد الثغرات؟"
make_file "$DIR" "Data_Privacy.md" "كيف نحمي بيانات المستخدمين؟ (تشفير،retention، حذف)"
make_file "$DIR" "Scalability_Plan.md" "كيف نتعامل مع الضغط العالي؟ Horizontal/Vertical Scaling?"

# ────────────────────────────────────────────────────────────────────────────
# 09_Testing_and_QA
# ────────────────────────────────────────────────────────────────────────────
DIR="09_Testing_and_QA"
make_file "$DIR" "Test_Cases.md" "ما حالات الاختبار لتغطية المنطق البرمجي؟ (Happy path + Error)"
make_file "$DIR" "Edge_Cases.md" "ما المدخلات النادرة أو الخاطئة المتوقعة؟ وكيف يتعامل النظام؟"

# ── Final README ────────────────────────────────────────────────────────────
cat > "$ANALYSIS_DIR/README.md" <<README
# ${PROJECT_NAME} — Project Analysis Workspace

> تم الإنشاء تلقائياً بواسطة \`new-project.sh\`
> التاريخ: $(date +%Y-%m-%d)

## الهيكل

| # | المجلد | الملفات | السؤال |
|---|--------|---------|--------|
| 01 | Business & Vision | 4 | لماذا نبني هذا؟ |
| 02 | Requirements Engineering | 4 | ماذا نبني بالضبط؟ |
| 03 | System Architecture | 4 | كيف نبنيها؟ |
| 04 | Database Design | 3 | أين نخزن البيانات؟ |
| 05 | API & Integrations | 3 | كيف نربط الخدمات؟ |
| 06 | UI/UX Design | 3 | كيف سيتفاعل المستخدم؟ |
| 07 | DevOps & Deployment | 4 | كيف نشغلها؟ |
| 08 | Security & Risks | 3 | كيف نحميها؟ |
| 09 | Testing & QA | 2 | كيف نضمن الجودة؟ |

ابدأ من \`01_Business_and_Vision\` واتبع الترتيب.

## ملاحظات

- املأ كل ملف بالإجابات عن السؤال في عنوانه
- استخدم **Mermaid.js** للرسوم البيانية (لا ASCII)
- كل ملف يجب أن يحتوي أرقاماً حقيقية
README

# ── Done ────────────────────────────────────────────────────────────────────
echo -e "  ${GREEN}✅ Created ${ANALYSIS_DIR}/ with 9 directories, 30 files${NC}"
echo ""
echo -e "  ${CYAN}📂 ${ANALYSIS_DIR}/$(ls -1 "$ANALYSIS_DIR" | head -1)${NC}"
for d in "$ANALYSIS_DIR"/*/; do
  count=$(find "$d" -maxdepth 1 -type f | wc -l)
  name=$(basename "$d")
  echo -e "  ${CYAN}📂 ${name}/ (${count} files)${NC}"
done | sort
echo ""
echo -e "  ${YELLOW}Next: cd ${ANALYSIS_DIR} && ls -R${NC}"
echo -e "  ${YELLOW}Start with: nano 01_Business_and_Vision/Business_Model_Canvas.md${NC}"
echo ""
